### ISSUE TITLE
Factor lost latency packets into packet loss calculations

### ISSUE THREAD

**Issue by k-rister** [atheurer/trafficgen#11]

**Comment by k-rister** [comment]
I no longer think this is broken.  Lost latency packets appear to be getting tracked in the bulk packet loss counters.  Maybe they are also being tracked in the received packet counters as well.  This would mean there is no need to account for them when doing throughput calculations.  Need to investigate further.  Leaving this issue open until the behavior is completely understood.

**Comment by atheurer** [comment]
Actually the lost latency packets should not be accounted for in the bulk network test.  Here is an example:

`[Histogram` port 0 to port 1] Samples: 4241, Average: 8726.3 ns, StdDev: 1069.2 ns, Quartiles: 8381.0/8557.0/8740.0 ns
[INFO]  Saving histogram to 'hist:0-1.csv'
[WARN]  [Histogram port 0 to port 1] Lost 316 samples (6.93%)!
[Histogram port 1 to port 0] Samples: 4228, Average: 8605.5 ns, StdDev: 940.2 ns, Quartiles: 8282.0/8470.0/8672.0 ns
[INFO]  Saving histogram to 'hist:1-0.csv'
[WARN]  [Histogram port 1 to port 0] Lost 328 samples (7.20%)!
[Device: id=0] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Device: id=1] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Device: id=0] RX: 9.70 (StdDev 3.55) Mpps, 4968 (StdDev 1817) Mbit/s (6520 Mbit/s with framing), total 329887235 packets with 21112855936 bytes (incl. CRC)
[Device: id=1] RX: 9.70 (StdDev 3.55) Mpps, 4968 (StdDev 1819) Mbit/s (6520 Mbit/s with framing), total 329877723 packets with 21112247184 bytes (incl. CRC)
[PARAMETERS] startRate: 11.000000 nrFlows: 1024 frameSize: 64 runBidirec: true latencyRunTime: 30 ports: 1,2
[REPORT]Device 0->1: Tx frames: 329877723 Rx Frames: 329877723 frame loss: 0, 0.000000% Rx Mpps: 10.996740
[REPORT]Device 1->0: Tx frames: 329887235 Rx Frames: 329887235 frame loss: 0, 0.000000% Rx Mpps: 10.996740
[REPORT]      total: Tx frames: 659764958 Rx Frames: 659764958 frame loss: 0, 0.000000% Tx Mpps: 21.993479 Rx Mpps: `21.993479`

However, I don't think the lost latency packets should be counted as lost by the device-under-test.  The  problem is that the lost latency packets are usually not lost at all.  The MoonGen latency code seems to have problems in accounting for all packets, so we can distinguish between truly lost packets and packets that are not received properly.
