### ISSUE TITLE
Add timestamping/way to track progress on long running tests

### ISSUE THREAD

**Issue by k-rister** [atheurer/trafficgen#12]
When a long test is running (ex. multi-hour validation) it is impossible to know when the attempt started so as to gauge how much time remains.  The longer a test goes (ie. attempts fail causing more search runs and validations) it gets increasingly difficult to figure out where in the process the run is.

**Comment by k-rister** [comment]
I would be willing to take a shot at this but I think @atheurer had some thoughts on this already.  Can you share what you were thinking?

**Comment by atheurer** [comment]
So, are thinking of time-stamping each status line (TX and RX stats) with something like epoch time?  I am in favor of that, as I want to graph this anyway.

**Comment by k-rister** [comment]
That is maybe a little further than my initial thoughts, but in a good way.  I wasn't sure you would want to go that far so that is interesting to read.  I'm open to anything that will allow me know that a validation attempt started at time X and now is time Y so it's been running for X-Y time allowing me to figure out how much time is remaining.  Anything beyond that is icing on the cake.

**Comment by atheurer** [comment]
I wonder, would you like to have some kind of output, perhaps once/minute, that shows time remaining for the current measurement?

I am probably in favor of both, a timestamp per rx/tx line stat, and the occasional remaining time info line.

**Comment by k-rister** [comment]
That would work just fine.
