### ISSUE TITLE
Incorrect requirements for README-binary-search.md

### ISSUE THREAD

**Issue by drchristensen** [atheurer/trafficgen#132]
The README file for the binary-search.py script incorrectly specifies a requirement for T-Rex v2.22, resulting in the following failure:

# ./binary-search.py --help
Traceback (most recent call last):
  File "./binary-search.py", line 5, in <module>
    from trex_tg_lib import *
  File "/home/drc/src/trafficgen/trex_tg_lib.py", line 7, in <module>
    from trex.stl.api import *
ModuleNotFoundError: No module named 'trex'

This is the offending line in trex_tg_lib.py:
sys.path.append('/opt/trex/current/automation/trex_control_plane/interactive')

The T-Rex v2.22 release does not include an "interactive" directory.

**Comment by k-rister** [comment]
This README is way out of date and needs to be updated, but in the meantime there is a script that handles TRex installation for you called install-trex.sh.

**Comment by k-rister** [comment]
There have been quite a few README updates and there is one more in progress that should allow this to be closed.
