### ISSUE TITLE
Latency measurement breaks at high throughput

### ISSUE THREAD

**Issue by k-rister** [atheurer/trafficgen#8]
Somewhere between 9-10 Mpps each direction the packet latency measurements completely fall apart with the packets getting lost.

**Comment by atheurer** [comment]
When using the latest phobos code, this is at least reduced to levels which I would deem "minimally acceptable".  I have tested with bi-directional throughput of ~22Mpps, and I now get only 7% loss.  Previously, all of the packets would be lost.
